### ISSUE TITLE
PyOpenGL_accelerate install issues

### ISSUE THREAD

**Issue by dldatwyler** [usuaero/Pylot#2]
PyOpenGL_accelerate has wheel problems when using "pip install ." per the directions.

How do I get the PyOpenGL_accelerate to install?

**Comment by dldatwyler** [comment]
after using activestate for an environment, I get:
python -m pylot cnb1.json
pygame 2.1.2 (SDL 2.0.18, Python 3.10.1)
Hello from the pygame community. https://www.pygame.org/contribute.html

-----------------------------------------------------
|                                                   |
|                    Pylot 1.3.4                    |
|                                                   |
|               (c) USU AeroLab 2020                |
|                                                   |
|             This software comes with              |
|    ABSOLUTELY NO WARRANTY EXPRESSED OR IMPLIED    |
|                                                   |
|           Submit bug reports on Github.           |
|                                                   |
-----------------------------------------------------
Traceback (most recent call last):
  File "c:\users\dldat\appdata\local\activestate\cache\87885070\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\dldat\appdata\local\activestate\cache\87885070\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\dldat\AppData\Roaming\Python\Python310\site-packages\pylot\__main__.py", line 25, in <module>
    simulate(input_filename)
  File "C:\Users\dldat\AppData\Roaming\Python\Python310\site-packages\pylot\__main__.py", line 13, in simulate
    sim = Simulator(input_dict, verbose=True)
  File "C:\Users\dldat\AppData\Roaming\Python\Python310\site-packages\pylot\simulator.py", line 58, in __init__
    self._render_graphics = self._input_dict["simulation"].get("enable_graphics", False)
KeyError: 'simulation'

**Comment by dldatwyler** [comment]
same issue in ab Anaconda power shell window

**Comment by corygoates** [comment]
OpenGL is something that I've always had a hard time getting to work. If you manage to figure this out, please let me know!

**Comment by timijab** [comment]
I used the python 3.9 version and the build was successful !!

**Comment by corygoates** [comment]
Great to hear!
